### ISSUE TITLE
Cannot boot into installer

### ISSUE THREAD

**Issue by huskytech9** [Swung0x48/Dell-Latitude-7390-7490-Hackintosh-EFI#15] opened 2020-07-04 23:45 UTC
Hi
I use your EFI folder. But my dell 7490 never boot on mac os. I can hear MAC OS Boot sound and then it boot to Windows.
Any ideas what I am doing wrong !

**Comment by Swung0x48** [comment] 2020-07-05 01:03
Please use an plist editor(such as [ProperTree](https://github.com/corpnewt/ProperTree))
Add `-v` to `NVRAM` -> `7C436110-AB2A-4BBB-A880-FE41995C9F82` -> `boot-args`
Then boot into macOS then report where it stuck at.

**Comment by huskytech9** [comment] 2020-07-05 02:10
Thanks 
Not sure where to put -v
I did put other value as shown below...... Let me know please
![image](https://user-images.githubusercontent.com/63915924/86524030-215c3a00-be43-11ea-857d-d9de77060316.png)

**Comment by Swung0x48** [comment] 2020-07-05 02:47
Modify the value of key `boot-args` to `-v debug=0x100`.

**Comment by huskytech9** [comment] 2020-07-05 03:01
Thank for reply. I am bit confused here of what to enter or not. 
Do I remove first value of 7C436110-AB2A-4BBB-A880-FE41995C9F82. ??
Could you please help to understand what is the complete value for boot-argument under nvram?

**Comment by Swung0x48** [comment] 2020-07-05 03:17
`7C436110-AB2A-4BBB-A880-FE41995C9F82` is a dictionary, which includes some key-value pairs. In which there is a key-value pair whose key is `boot-args`, and its type is `String`. Change the value of that key-value pair to `-v debug=0x100`. It should be just the boot-args you will need for the time being. 
If you are worried about a previously messy NVRAM, you can smash `Esc` when booting into OpenCore and then select `Reset NVRAM` after the OpenCore boot picker shows up. 
(You may also use `Command/Alt` + `Shift` + `P` + `R`, but the hotkey occasionally breaks)

**Comment by Swung0x48** [comment] 2020-07-05 03:29
> Thank for reply. I am bit confused here of what to enter or not. 
> 
> Do I remove first value of 7C436110-AB2A-4BBB-A880-FE41995C9F82. ??
> 
> Could you please help to understand what is the complete value for boot-argument under nvram?

![image](https://user-images.githubusercontent.com/16967689/86524843-41771200-beb2-11ea-848c-00366fa0cae5.jpeg)
If you really want explanation in picture, then here you are.
(I just thought that editor is pretty much self-explanatory...

**Comment by huskytech9** [comment] 2020-07-05 04:55
I really appreciate your help. I will try again tomorrow and let you the results

**Comment by huskytech9** [comment] 2020-07-05 20:55
Now I am able to boot. Disk utility now show my USB drives. Seems like hard drive is not detecting
![1C3C55E9-B35D-4478-8309-D71F52677787](https://user-images.githubusercontent.com/63915924/86542083-33d88100-bee0-11ea-87bd-52f9a5547ff9.jpeg)

**Comment by Swung0x48** [comment] 2020-07-06 01:15
Since the previous problem is resolved, this issue will be closed by now. 
Please open a new issue if there's a new question and provide adequate info ahead of time for me to troubleshoot.
Also, plz leave the solution after the problem is solved. Not just showing 'it is solved lol'.
For a new problem, plz open a new issue.

**Comment by huskytech9** [comment] 2020-07-06 01:31
Solution is followed boot arg to -v debug=0x100
Then I was able to boot into install 
Thanks

**Comment by Swung0x48** [comment] 2020-07-06 01:33
> Solution is followed boot arg to -v debug=0x100
> Then I was able to boot into install
> Thanks

FYI, this is definitely not a solution to this. It just enables verbose mode, which enables more info to be outputted.

**Comment by xwhl** [comment] 2020-07-19 10:30
Excuse me, I had the same problem with @huskytech9 that I heard a boot sound , then it jumped to the next boot option. I had add "-v debug=0x100", but it still make a sound and jump to the next boot option, without verbose output. BTW, my device is latitude 7390 , and I had installed your clover version successfully.
Could you plz give me some advice?

**Comment by Swung0x48** [comment] 2020-07-19 10:43
Find ShowBootPicker in config.plist and set it to True. It should show the boot picker rather that just skip it.

**Comment by xwhl** [comment] 2020-07-19 11:15
> Find ShowBootPicker in config.plist and set it to True. It should show the boot picker rather that just skip it.
It works, thanks. I tried several times, and the verbose outputs are different. BTW, to install the clover version, I had to add boot-arg:"USBBusFix=Yes", does this matter in OpenCore?
![IMG_0611](https://user-images.githubusercontent.com/37295640/87873427-2c42cd00-c9f4-11ea-8ed0-b0725e130d54.JPG)
![IMG_0610](https://user-images.githubusercontent.com/37295640/87873432-32d14480-c9f4-11ea-9a15-e0f685e77ad0.JPG)
![IMG_0609](https://user-images.githubusercontent.com/37295640/87873434-35339e80-c9f4-11ea-8fd4-885926b9f76f.JPG)
![IMG_0608](https://user-images.githubusercontent.com/37295640/87873437-382e8f00-c9f4-11ea-9c08-ae301183277f.JPG)

**Comment by Swung0x48** [comment] 2020-07-19 12:04
You may have a try.(I don't know what does that arg do)
Search for `boot-args` in `config.plist` and put that in there.

**Closed as completed** 2020-07-21 01:53 UTC
Labels: invalid, Boot
